IPBV-Blessed-Bytes/IPBV-camp-form-FE

src/Pages/ChooseFormPayment/index.jsx
src/Pages/Home/index.jsx
src/Pages/Packages/index.jsx
src/Pages/Routes/index.jsx
src/styles/Style.scss
src/styles/Variables.scss

- Atualizando header para receber um link
- Atualizado estado inicial da aplicação para homepage
- Atualiando chamada da mensagem do componente de sucesso
- Atualizando componente de pacotes para mostrar desconto em transporte

Add package hotel to show hotel values correctly

---

src/Pages/Packages/index.jsx
src/Pages/Packages/utils/packages.js
src/Pages/Success/index.jsx
src/components/Header.jsx
src/styles/Style.scss

- Atualizar header para receber um link no título principal
- Atualziar mensagem do componente de sucesso
- Atualizar componente de pacotes para mostrar desconto de transporte

Update packages component to show discount

---

package.json
src/Pages/Routes/index.jsx
yarn.lock

- Adicionando dependencia do axios e chamada de API

Add axios dependency

---

src/Pages/Routes/index.jsx

Update request body

---

package.json
src/Pages/Packages/index.jsx
src/Pages/Packages/utils/packages.js
src/Pages/Routes/index.jsx
src/Pages/Success/index.jsx
src/main.jsx
yarn.lock

- Adicionado biblioteca toastify
- Atualizado msg de desconto
- Adicionado funcionalidade para avançár tela de pagamento se preço for zero

Feat: Add funcionality to skip payment step if the price is 0

---

src/Pages/ChooseFormPayment/index.jsx
src/Pages/Packages/index.jsx
src/Pages/Routes/index.jsx

Add pagar.me in FE

---

src/Pages/ChooseFormPayment/index.jsx
src/Pages/Routes/index.jsx

Bugfix: Call API [revert]

---

src/Pages/ChooseFormPayment/index.jsx
src/Pages/Packages/index.jsx
src/Pages/Packages/utils/packages.js
src/Pages/Success/index.jsx
src/styles/Style.scss

- Adicionado novas proptypes
- Atualizado validações dos pacotes

Update packages validations

---

src/Pages/Routes/index.jsx
src/Pages/Success/index.jsx
src/components/Header.jsx

- Adicionado funcionalidade para impedir que após submeter o form e estiver na tela de sucesso, possa voltar pelo navbar

Feat: prevent returning to nav after submitting form

---

src/Pages/ChooseFormPayment/index.jsx
src/Pages/Routes/index.jsx
src/Pages/Success/index.jsx
src/components/Header.jsx

[API] Waiting backend test  @alvarolealdl

---

src/Pages/ChooseFormPayment/index.jsx
src/Pages/Packages/index.jsx
src/Pages/Packages/utils/generatePackagesValues.js
src/Pages/Packages/utils/packages.js
src/Pages/Routes/index.jsx

- Resoluções de bugs e refatoração do código

Formpayment bug

---

src/App.jsx

- Adicionando google form no projeto

adding google form

---

src/Pages/Admin/index.jsx
src/Pages/ChooseFormPayment/index.jsx
src/Pages/Contact/index.jsx
src/Pages/Home/index.jsx
src/Pages/Packages/index.jsx
src/Pages/Packages/utils/generatePackagesValues.js
src/Pages/Packages/utils/packages.js
src/Pages/Routes/index.jsx
src/Pages/Success/index.jsx
src/components/Footer.jsx
src/components/Header.jsx
src/components/Icon.jsx
src/styles/Style.scss

- Ajustando todos componentes (sucesso, homepage, pacotes, etc)
- Ajustando estilo de tudo
- Adicionando tela de admin

Final adjustments to components and adding admin screen

---

src/App.jsx
src/Pages/ChooseFormPayment/index.jsx
src/Pages/CloseForm/index.jsx
src/Pages/Contact/index.jsx
src/Pages/FinalReview/index.jsx
src/Pages/Offline/index.jsx
src/Pages/Packages/index.jsx
src/Pages/Packages/utils/generatePackagesValues.js
src/Pages/Packages/utils/packages.js
src/Pages/PersonalData/data.js
src/Pages/PersonalData/index.jsx
src/Pages/Routes/index.jsx
src/Pages/Success/index.jsx
src/components/Footer.jsx
src/components/Header.jsx
src/form/validations/schema.js
src/styles/Style.scss

Final Adjusts 4

---

src/App.jsx

close form

---

src/App.jsx
src/Pages/Packages/index.jsx

[Hotfix] Camping package name

---

netlify.toml

fix: adding router configuration

---

src/Pages/Packages/utils/generatePackagesValues.js
src/styles/Style.scss

Fix packages price

---

package-lock.json
package.json
src/Pages/Admin/admin.jsx
src/Pages/Routes/index.jsx
src/config/index.js
src/fetchers/fetcherWithCredentials.js
src/fetchers/helpers.js
src/fetchers/index.js
src/hooks/useAuth/AuthProvider.jsx
src/hooks/useAuth/helpers.js
src/hooks/useAuth/index.js
src/main.jsx

feature: creating useAuth hook and setting fetcher

---

src/Pages/Admin/adminComponents/adminCoupon.jsx
src/Pages/Admin/adminComponents/adminRide.jsx
src/Pages/Admin/adminComponents/adminTable.jsx

- Utilização dos fetchers privados nos componentes de admin

fix: using private fetcher on admin components

---

src/Pages/Admin/adminComponents/adminCoupon.jsx
src/Pages/Admin/adminComponents/adminRide.jsx
src/Pages/Admin/adminComponents/adminTable.jsx
src/Pages/Admin/adminComponents/adminTableColumns.jsx
src/Pages/Admin/adminComponents/adminTableField.jsx
src/components/Loading.jsx
src/styles/Style.scss

Update logic to show error in the admin table component

---

src/Pages/Admin/adminComponents/adminTableColumns.jsx
src/Pages/Routes/index.jsx

Add non paid form payment option and update nested field logic

---

src/styles/Style.scss

Fix whatsapp button to don't overlay toast's

---

src/Pages/Routes/index.jsx
src/fetchers/fetcherWithCredentials.js

https://github.com/user-attachments/assets/c97474b4-2109-4517-9bcd-fe12b219feb8

showing fetch error message  using toast
